apiVersion: v1
kind: Template
metadata:
  name: minio-webhook-template.yml
parameters:
  - name: WSK_AUTH
    description:  the username/password for openwhisk (wsk property get --auth)
objects:
- apiVersion: v1
  data:
    WSKAUTH: "${WSK_AUTH}"
  kind: Secret
  metadata:
    labels:
      app: minio-webhook
    name: wsk-secret
  type: Opaque
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: minio-webhook
    name: minio-webhook
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: minio-webhook
      deploymentconfig: minio-webhook
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 1
    labels:
      app: minio-webhook
    name: minio-webhook
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/minio/minio-webhook:latest
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/image.dockerRepositoryCheck: 2018-04-16T20:45:42Z
    generation: 2
    labels:
      app: minio-webhook
    name: nodejs-8-centos7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: centos/nodejs-8-centos7
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/minio/nodejs-8-centos7:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: minio-webhook
    name: minio-webhook
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: minio-webhook:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/stephanosbacon/minio-webhook.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs-8-centos7:latest
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: d3mOU4eMJlPsEiyinJv2
      type: GitHub
    - generic:
        secret: tvJZWGJqU_sXZ_VwRLLJ
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 1
    labels:
      app: minio-webhook
    name: minio-webhook
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: minio-webhook
      deploymentconfig: minio-webhook
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        labels:
          app: minio-webhook
          deploymentconfig: minio-webhook
      spec:
        containers:
        - envFrom:
          - secretRef:
              name: wsk-secret
          image: docker-registry.default.svc:5000/minio/minio-webhook
          imagePullPolicy: Always
          name: minio-webhook
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - minio-webhook
        from:
          kind: ImageStreamTag
          name: minio-webhook:latest
          namespace: minio
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
